package experimentpolicy

import "fmt"

const OrigamiCandidateSpecSchemaR0 = "origami.experimental-candidate.r0"

type OrigamiMutation struct {
	Kind         string `json:"kind"`
	Target       string `json:"target"`
	Value        string `json:"value"`
	Rationale    string `json:"rationale,omitempty"`
	Experimental bool   `json:"experimental"`
}

type OrigamiCandidateSpec struct {
	Schema       string            `json:"schema"`
	ID           string            `json:"id"`
	ParentSHA256 string            `json:"parent_sha256,omitempty"`
	Mutations    []OrigamiMutation `json:"mutations"`
}

func ToOrigamiSpec(c CandidateManifest, parentSHA string) (OrigamiCandidateSpec,error) {
	if c.Schema!=CandidateSchemaR1{return OrigamiCandidateSpec{},fmt.Errorf("unexpected candidate schema %q",c.Schema)}
	if c.ID==""||len(c.Mutations)==0{return OrigamiCandidateSpec{},fmt.Errorf("candidate id and mutations are required")}
	out:=OrigamiCandidateSpec{Schema:OrigamiCandidateSpecSchemaR0,ID:c.ID,ParentSHA256:parentSHA}
	for _,m:=range c.Mutations{out.Mutations=append(out.Mutations,OrigamiMutation{Kind:m.Kind,Target:m.Target,Value:m.Value,Rationale:"generated by guarded Tlaloc learning cycle",Experimental:true})}
	return out,nil
}
